version: "3"
services:
  hmpps-mailbox-register-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-mailbox-register-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev
      - DB_SERVER=mailbox-register-db
      - DB_NAME=mailbox-register-db
      - DB_USER=mailbox-register
      - DB_PASS=dummy-password
    depends_on:
      - mailbox-register-db

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  mailbox-register-db:
    image: postgres:16.4
    networks:
      - hmpps
    container_name: mailbox-register-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mailbox-register-db
      - POSTGRES_USER=mailbox-register
      - POSTGRES_PASSWORD=dummy-password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d mailbox-register-db -U mailbox-register" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  hmpps:

volumes:
  pgdata:
