hmpps-auth:
  url: "${HMPPS_AUTH_URL:http://localhost:8090/auth}"

spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
