name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 * * 1" # Every Monday
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v0.7 # WORKFLOW_VERSION
    with:
      channel_id: the_elephants_devs
    secrets: inherit
