name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "59 9 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: moic-alerts
    secrets: inherit
