name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "59 9 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: the_elephants_devs
    secrets: inherit
